export enum ActionTypes {
  /* Auth Actions */
  SET_LOGIN_INFO = 'SET_LOGIN_INFO',
  SET_TOKEN = 'SET_TOKEN',
  SET_LOGOUT = 'SET_LOGOUT',
  SET_USER_LOADING = 'SET_USER_LOADING',
  SET_USER_ERRORS = 'SET_USER_ERRORS',

  /* Project Actions */
  SET_CURRENT_PROJECT = 'SET_CURRENT_PROJECT',
  SET_USER_PROJECTS = 'SET_USER_PROJECTS',
  SET_USER_ORGANISATION = 'SET_USER_ORGANISATION',
  SET_PROJECT_LOADING = 'SET_PROJECT_LOADING',

  /* Issue Actions */
  SET_ASSIGNED_ISSUES = 'SET_ASSIGNED_ISSUES',
  SET_PROJECT_ISSUES = 'SET_PROJECT_ISSUES',
  SET_ISSUE_LOADING = 'SET_ISSUE_LOADING',

  /* Organisation invitation Actions */
  SET_USER_ORGANISATION_INVITATIONS = 'SET_USER_ORGANISATION_INVITATIONS',
  SET_ALL_ORGANISATION_INVITATIONS = 'SET_ALL_ORGANISATION_INVITATIONS',
  SET_ORGANISATION_INVITATIONS_LOADING = 'SET_ORGANISATION_INVITATIONS_LOADING'
}
