export enum ActionTypes {
  /* Auth Actions */
  SET_LOGIN_INFO = 'SET_LOGIN_INFO',
  SET_TOKEN = 'SET_TOKEN',
  SET_LOGOUT = 'SET_LOGOUT',
  SET_USER_LOADING = 'SET_USER_LOADING',
  SET_USER_ERRORS = 'SET_USER_ERRORS',

  /* Project Actions */
  SET_SELECTED_PROJECT = 'SET_SELECTED_PROJECT',
  SET_ORGANISATION_PROJECTS = 'SET_ORGANISATION_PROJECTS',
  SET_USER_ORGANISATION = 'SET_USER_ORGANISATION',
  SET_PROJECT_ACTIVE_MEMBERS = 'SET_PROJECT_ACTIVE_MEMBERS',
  SET_PROJECT_SPRINTS = 'SET_PROJECT_SPRINTS',
  SET_NOT_COMPLETED_SPRINTS = 'SET_NOT_COMPLETED_SPRINTS',
  SET_PROJECT_LAST_ISSUES = 'SET_PROJECT_LAST_ISSUES',
  SET_PROJECT_LOADING = 'SET_PROJECT_LOADING',

  /* Sprint Actions */
  SET_SELECTED_SPRINT = 'SET_SELECTED_SPRINT',
  SET_SPRINT_ISSUES = 'SET_SPRINT_ISSUES',
  SET_SPRINT_ACTIVE_MEMBERS = 'SET_SPRINT_ACTIVE_MEMBERS',
  SET_SPRINT_LOADING = 'SET_SPRINT_LOADING',

  /* Issue Actions */
  SET_ASSIGNED_ISSUES = 'SET_ASSIGNED_ISSUES',
  SET_ISSUE_LOADING = 'SET_ISSUE_LOADING',
  SET_ISSUES_UNASSIGNED_TO_SPRINT = 'SET_ISSUES_UNASSIGNED_TO_SPRINT',
  SET_BOARD_ISSUES = 'SET_BOARD_ISSUES',

  /* Organisation Actions */
  SET_UNASSIGNED_USERS = 'SET_UNASSIGNED_USERS',
  SET_ORGANISATION_LOADING = 'SET_ORGANISATION_LOADING',

  /* Organisation invitation Actions */
  SET_USER_ORGANISATION_INVITATIONS = 'SET_USER_ORGANISATION_INVITATIONS',
  SET_ALL_ORGANISATION_INVITATIONS = 'SET_ALL_ORGANISATION_INVITATIONS',
  SET_ORGANISATION_INVITATIONS_LOADING = 'SET_ORGANISATION_INVITATIONS_LOADING'
}
