DROP TABLE IF EXISTS projects;
CREATE TABLE projects(
    id UUID PRIMARY KEY NOT NULL,
    name VARCHAR(30) NOT NULL,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL ,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
)